version: "3.2"

services:
    devcode:
        image: duartej/corryvreckan:latest
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR_CORRY
              target: /analysis/corryvreckan
            - type: bind
              source: @DATAANADIR
              target: /data
            - type: bind
              source: @ANADIR
              target: /testbeam
        environment:
            - DISPLAY=unix${DISPLAY}
